### ISSUE TITLE
请问用的是那块主板呢?

### ISSUE THREAD

**Issue by FENGYINYUANYOU** [YCF/Hackintosh-EFI-for-deskmini-310-i3-8100#10]
华硕的310  还是华擎的,,技嘉?

**Comment by YCF** [comment]
这个是准系统，自带主板。
https://item.jd.com/100008383356.html

**Comment by FENGYINYUANYOU** [comment]
明白,谢谢,,我用的是华硕的310T2,,可能用不了这个.... 小白一个,,,华擎 310主板和华硕310主板,,那个相对而言好呢?
