### ISSUE TITLE
转接线必须是这个型号？

### ISSUE THREAD

**Issue by Good0007** [YCF/Hackintosh-EFI-for-deskmini-310-i3-8100#4]
我买了个转接线不管用...

**Comment by YCF** [comment]
我买的这个线可以，因为是内置芯片的。
其他的我也不清楚了。

**Comment by Good0007** [comment]
嗯嗯 买了这个线可以。我们完美上10.14.1了  


(原回帖有QQ群号码，已编辑)

**Comment by Nero5023** [comment]
我在家用的是 dp to dp 的线没什么问题，装好后搬到学校用，买了京东绿联的另一根线，能进 Clover 界面但是系统进度条读到一半的时候没有信号了。现在买了 PS176 的线，下午到，希望能行...
